name: app 
description: for ice.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.4+6

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.0.0
  hydrated_bloc: ^8.0.0
  bloc_concurrency: ^0.2.0
  graphql: ^5.0.0
  flutter_webrtc: ^0.6.10+hotfix.1
  mediasoup_client_flutter: ^0.4.6
  equatable: ^2.0.3
  flutter_local_notifications: ^9.0.0
  # firebase_core: ^1.7.0
  # firebase_messaging: ^10.0.8
  image_picker: ^0.8.4+2
  yaml: ^3.1.0
  logger: ^1.1.0
  google_fonts: ^2.0.0
  device_info_plus: ^3.1.1
  font_awesome_flutter: ^9.1.0
  auto_route: ^3.2.0
  infinite_scroll_pagination: ^3.0.1+1
  permission_handler: ^8.2.5
  chat_ui_kit: ^1.3.0
  path_provider: ^2.0.1
  json_annotation: ^4.3.0
  url_launcher: ^6.0.12
  oauth2: ^2.0.0
  built_value: ^8.0.4
  flutter_login: ^3.0.0
  jwt_decoder: ^2.0.1
  shared_preferences: ^2.0.6
  material_floating_search_bar: ^0.3.4
  share_plus: ^2.1.4
  badges: ^2.0.1
  intl: ^0.17.0
  extended_image: ^6.0.1
  expandable_bottom_sheet: ^1.1.1+1
  convex_bottom_bar: ^3.0.0
  http: ^0.13.4
  share_plus_web: ^2.0.4
  auto_start_flutter: ^0.0.8-nullsafety
  flutter_spinkit: ^5.1.0
  rfw: ^1.0.2
  flutter_bugly: ^0.3.3
  

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.0.0
  build_runner: ^2.1.4
  flutter_launcher_icons: ^0.9.0
  flutter_gen_runner: ^3.0.2
  flutter_native_splash: ^1.1.5+1
  flutter_lints: ^1.0.4
  auto_route_generator: ^3.0.1
  object_storage_repository:
    path: packages/object_storage_repository
  authentication_repository: 
    path: packages/authentication_repository
  account_repository:
    path: packages/account_repository
  pubsub_repository:
    path: packages/pubsub_repository
  contacts_repository:
    path: packages/contacts_repository
  message_repository:
    path: packages/message_repository
  p2p_signaling_repository:
    path: packages/p2p_signaling_repository
  ice_widget: 
    path: packages/ice_widget
  ice_util:
    path: packages/ice_util
  protoo_client: 
    path: packages/dart-protoo-client



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/configs/
    - assets/images/
    - assets/images/logo/
    - assets/images/login/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
