const kSignUpWithUserName = 'signUpWithUserName';
const kSignInWithUserName = 'signInWithUserName';
const kInput = 'input';
const kUserName = 'userName';
const kPassword = 'password';
const kErrorResultDataIsNull = 'result data is null';
const kSuccess = 'success';
const kId = 'id';
const kToken = 'token';
